name: beta

on:
  # Build main branch.
  push:
    branches:
      - main
  # Build all pull requests.
  pull_request:

jobs:
  test:
    name: beta on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
          components: rustfmt, clippy

      - name: Test default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all -- --nocapture

      - name: Test parser feature
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features -- --nocapture
